language: julia

os:
    - linux

julia:
    - 1.3

fast_finish: true
notifications:
    email: false
    
script:
    - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test(coverage=true)'
   
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
